#! /bin/bash
#SBATCH --mail-user=anthony.hauser@ispm.unibe.ch
#SBATCH --mail-type=end,fail
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=2G
#SBATCH --array=1-972
#SBATCH --output="outfiles/slurm-%A_%a.out"
#SBATCH --cpus-per-task=4

# Create paths, job number and date of job
PROJECT="usb_efficient_seir/ubelix/mod_perf_comparison"
JOB1="${SLURM_ARRAY_JOB_ID}"
JOB2=${SLURM_ARRAY_TASK_ID}
date=$(date +'%Y%m%d%H%M')
date="20220406"

# Sweeping parameters.txt
N=${SLURM_ARRAY_TASK_ID}
echo "$N"

ra=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f1`
rb=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f2`
rc=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f3`
rd=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f4`
re=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f5`
rf=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f6`
rg=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f7`
rh=`head -n ${N} parameters8.txt | tail -n 1 | cut -d' ' -f8`

# Paths to temporary file and out file
SCR="/storage/homefs/ahauser/projects/${PROJECT}/temp-$ra$rb$rc$rd$re$rf"
OUT="/storage/homefs/ahauser/projects/${PROJECT}/outfiles/mod4-$ra$rb$rc$rd$re$rf.Rout"

# Display
echo "Job array item $N: ra=$ra, rb=$rb, rc=$rc, rd=$rd, re=$re, rf=$rf, rg=$rg, rh=$date,"
echo "---------------------------------"
echo "8 parameters values assigned by array"

echo "$OUT"
echo "$date"

# Create temporary file, where the simulations are run
mkdir -p $SCR
cp -p run_mod4_ubelix.R $SCR/.
cd $SCR

# Load module 
module load R/4.1.0-foss-2021a

# Run R file
R CMD BATCH --no-save --no-restore "--args $ra $rb $rc $rd $re $rf $rg $date" run_mod4_ubelix.R

# Copy Rout file
cp run_mod4_ubelix.Rout $OUT
rm run_mod4_ubelix.Rout
rm -rf $SCR

echo "Job is done."
