---
title: "Extract CV"
output: html_document
---

```{r setup, include=FALSE}


library(INLA)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)


postpredchecks <- function(Y){
  
  pred.samples <- do.call(cbind, Y$prediction)
  true_values <- Y$true_values
  
  # samples from a Poisson
  set.seed(11)
  pois.samples <-  apply(pred.samples, 2, function(X) rpois(n = length(X), lambda = X))
  
  # calculate quantiles
  pois.quant <- as.data.frame(t(apply(pois.samples, 1, function(Z) quantile(Z, probs = c(0.025, 0.975)))))
  cov.prob = mean((pois.quant$`2.5%` <= true_values) & (pois.quant$`97.5%` > true_values))
  
  
  res <- list(
    correl = apply(pois.samples, 2, function(X) cor(X, true_values)), 
    cov.prob = mean((pois.quant$`2.5%` <= true_values) & (pois.quant$`97.5%` > true_values)), 
    MSE = apply(t(sweep(pred.samples, 1, true_values, "-"))^2, 2, mean), 
    bias = apply(t(sweep(pred.samples, 1, true_values, "-")), 2, mean)
  )
  
  return(res)
  
}


nointeractions <- readRDS("savepoint/popcv_nointeractions")
nointeractionsov <- readRDS("savepoint/popcv_nointeractionsov")
interactionsov <- readRDS("savepoint/popcv_interactionsov")
randomslope <- readRDS("savepoint/popcv_randomslope")
randomslopeov <- readRDS("savepoint/popcv_randomslopeov")
randomslopeintov <- readRDS("savepoint/popcv_randomslopeintov")

res_checks_noint <- lapply(nointeractions, postpredchecks)
res_checks_nointov <- lapply(nointeractionsov, postpredchecks)
res_checks_intov <- lapply(interactionsov, postpredchecks)
res_checks_ranslop <- lapply(randomslope, postpredchecks)
res_checks_ranslopov <- lapply(randomslopeov, postpredchecks)
res_checks_ranslopintov <- lapply(randomslopeintov, postpredchecks)

```


# Leave one year out

## Correlation

```{r}

# Correlation
lapply(list(res_checks_noint, res_checks_nointov, res_checks_intov, 
            res_checks_ranslop, res_checks_ranslopov, res_checks_ranslopintov), 
       function(Y){
         round(
           do.call(rbind, 
                   lapply(lapply(Y, function(X) X$correl), 
                          function(X) quantile(X, probs = c(0.50, 0.025, 0.975)))
           ), 
           digits = 3
         )
       }
)

```

## Coverage

```{r}

# Coverage
res_checks_plot <- data.frame(coverage = c(sapply(res_checks_noint, function(X)X$cov.prob), 
                                           sapply(res_checks_nointov, function(X)X$cov.prob), 
                                           sapply(res_checks_intov, function(X)X$cov.prob), 
                                           sapply(res_checks_ranslop, function(X)X$cov.prob),
                                           sapply(res_checks_ranslopov, function(X)X$cov.prob),
                                           sapply(res_checks_ranslopintov, function(X)X$cov.prob)),  
                              
                              type = rep(c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"), each = 10)
)

res_checks_plot$type <- factor(res_checks_plot$type, levels = c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"))

res_checks_plot %>% group_by(type) %>% summarise(medcov = median(coverage))

ggplot() + geom_boxplot(data = res_checks_plot, aes(x = type, y = coverage)) + theme_bw() + 
  geom_hline(yintercept = 0.95, col = "red", linetype = "dashed") + xlab("") + ylab("") + 
  ggtitle("Coverage proportion")-> p1




```

## Mean square error

```{r fig.width=12, fig.height=6}

rbind(do.call(rbind, 
              lapply(res_checks_noint, function(X) sqrt(X$MSE))), 
      do.call(rbind, 
              lapply(res_checks_nointov, function(X) sqrt(X$MSE))),
      do.call(rbind, 
              lapply(res_checks_intov, function(X) sqrt(X$MSE))),
      do.call(rbind, 
              lapply(res_checks_ranslop, function(X) sqrt(X$MSE))), 
      do.call(rbind, 
              lapply(res_checks_ranslopov, function(X) sqrt(X$MSE))), 
      do.call(rbind, 
              lapply(res_checks_ranslopintov, function(X) sqrt(X$MSE)))
) %>% 
  as_tibble(.name_repair = "unique") %>% 
  mutate(type = factor(rep(c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"), each = 10), 
                       levels = c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT")), 
         years = factor(rep(2010:2019, times = 6))) -> res_MSE

res_MSE <- gather(res_MSE, lp, MSE, `...1`:`...260`, factor_key=TRUE) %>% mutate(lp := NULL)

res_MSE %>% group_by(type) %>% summarise(medRMSE = median(MSE))

res_MSE %>% group_by(type, years) %>% summarise(medRMSE = median(MSE)) %>% 
  ggplot() + geom_line(aes(x = years, y = medRMSE, group = type, colour = type)) + 
  geom_point(aes(x = years, y = medRMSE, group = type, colour = type)) + 
  theme_bw() + scale_color_viridis_d() + ylab("RMSE")


ggplot() + geom_boxplot(data = res_MSE, aes(x = years, y = MSE, fill = type), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("RMSE")


# we can also pull them together
ggplot() + geom_boxplot(data = res_MSE, aes(x = type, y = MSE), outlier.size = 1) + 
  theme_bw() + scale_fill_viridis_d() + ylab("") + xlab("") + 
  ggtitle("RMSE") -> p3



```

## Mean bias

```{r fig.width=12, fig.height=6}

rbind(do.call(rbind, 
              lapply(res_checks_noint, function(X) X$bias)), 
      do.call(rbind, 
              lapply(res_checks_nointov, function(X) X$bias)), 
      do.call(rbind, 
              lapply(res_checks_intov, function(X) X$bias)),
      do.call(rbind, 
              lapply(res_checks_ranslop, function(X) X$bias)),
      do.call(rbind, 
              lapply(res_checks_ranslopov, function(X) X$bias)), 
      do.call(rbind, 
              lapply(res_checks_ranslopintov, function(X) X$bias))
) %>% 
  as_tibble(.name_repair = "unique") %>% 
  mutate(type = factor(rep(c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"), each = 10), 
                       levels = c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT")), 
         years = factor(rep(2010:2019, times = 6))) -> res_bias

res_bias <- gather(res_bias, lp, bias, `...1`:`...260`, factor_key=TRUE) %>% mutate(lp := NULL)
ggplot() + geom_boxplot(data = res_bias, aes(x = years, y = bias, fill = type), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("Mean bias") 



res_bias %>% group_by(type) %>% summarise(medbias = median(bias))

res_bias %>% group_by(type, years) %>% summarise(medbias = median(bias)) %>% 
  ggplot() + geom_line(aes(x = years, y = medbias, group = type, colour = type)) + 
  geom_point(aes(x = years, y = medbias, group = type, colour = type)) + 
  theme_bw() + ylab("Median of mean bias") + ylim(c(-200, 200)) + 
  geom_hline(yintercept = 0, linetype = "dashed")


pcomp <- 
  res_bias %>% filter(type == "VC") %>% 
  ggplot() + geom_boxplot(aes(x = years, y = bias), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("Mean bias") |
  
  res_bias %>% filter(type == "VC_OV") %>% 
  ggplot() + geom_boxplot(aes(x = years, y = bias), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("Mean bias") 

  res_bias %>% filter(type == "OV_INT") %>% 
  ggplot() + geom_boxplot(aes(x = years, y = bias), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("Mean bias") 
  
pcomp


# we can also pull them together
ggplot() + geom_boxplot(data = res_bias, aes(x = type, y = bias), outlier.size = 1) + 
  theme_bw() + scale_fill_viridis_d() + ylab("") + xlab("model") + 
  ggtitle("Mean bias") + geom_hline(yintercept = 0, linetype = "dashed", col = "red") -> p2




```

```{r fig.width=15, fig.height=6}

p1|p2|p3


```

# Leave last 3 years out



```{r cars}

setwd("E:/Postdoc Imperial/Projects/COVID19 Greece/covid19_ascertain_deaths/")

nointeractions <- readRDS("savepoint/popcv3y_nointeractions")
nointeractionsov <- readRDS("savepoint/popcv3y_nointeractionsov")
interactionsov <- readRDS("savepoint/popcv3y_interactionsov")
randomslope <- readRDS("savepoint/popcv3y_randomslope")
randomslopeov <- readRDS("savepoint/popcv3y_randomslopeov")
randomslopeintov <- readRDS("savepoint/popcv3y_randomslopeintov")

res_checks_noint <- postpredchecks(nointeractions)
res_checks_nointov <- postpredchecks(nointeractionsov)
res_checks_intov <- postpredchecks(interactionsov)
res_checks_ranslop <- postpredchecks(randomslope)
res_checks_ranslopov <- postpredchecks(randomslopeov)
res_checks_ranslopintov <- postpredchecks(randomslopeintov)


data.frame(coverage = c(res_checks_noint$cov.prob, 
                        res_checks_nointov$cov.prob, 
                        res_checks_intov$cov.prob, 
                        res_checks_ranslop$cov.prob,
                        res_checks_ranslopov$cov.prob,
                        res_checks_ranslopintov$cov.prob),  
           
           type = rep(c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"))
)

data.frame(RMSE = sqrt(c(res_checks_noint$MSE, 
                        res_checks_nointov$MSE, 
                        res_checks_intov$MSE, 
                        res_checks_ranslop$MSE,
                        res_checks_ranslopov$MSE,
                        res_checks_ranslopintov$MSE)),  
           
           type = factor(c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"), 
                         levels = c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"))) -> res_MSE

ggplot() + geom_boxplot(data = res_MSE, aes(x = type, y = RMSE), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("RMSE")
res_MSE %>% group_by(type) %>% summarize(med = median(RMSE))

data.frame(bias = c(res_checks_noint$bias, 
                         res_checks_nointov$bias, 
                         res_checks_intov$bias, 
                         res_checks_ranslop$bias,
                         res_checks_ranslopov$bias,
                         res_checks_ranslopintov$bias),  
           
           type = factor(c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"), 
                         levels = c("BASE", "OV", "OV_INT", "VC", "VC_OV", "VC_OV_INT"))) -> res_bias

ggplot() + geom_boxplot(data = res_bias, aes(x = type, y = bias), outlier.size = 1.2) + 
  theme_bw() + scale_fill_viridis_d() + ylab("bias")
res_bias %>% group_by(type) %>% summarize(med = median(bias))





```
